name: Docker CI

on:
  push:
    paths:
      - ".github/workflows/docker-ci.yml"
  pull_request:
    branches:
      - main

jobs:
  docker:
    name: Docker compose up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker compose up
        run: docker compose up -d
